# Generated by Django 5.2 on 2025-04-09 12:16

import Registration.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('student_number', models.CharField(max_length=10)),
                ('branch', models.CharField(choices=[('CSE', 'CSE'), ('CS', 'CS'), ('CS-IT', 'CS-IT'), ('CSE-DS', 'CSE-DS'), ('CS-HINDI', 'CS-HINDI'), ('CSE-AIML', 'CSE-AIML'), ('IT', 'IT'), ('AIML', 'AIML'), ('ECE', 'ECE'), ('ME', 'ME'), ('EN', 'EN'), ('CIVIL', 'CIVIL')], max_length=10)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('year', models.CharField(choices=[('1st', '1st Year'), ('2nd', '2nd Year'), ('3rd', '3rd Year'), ('4th', '4th Year')], max_length=10)),
                ('phone', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Phone number must be 10-12 digits', regex='^\\d{10,12}$')])),
                ('email', models.EmailField(max_length=254, unique=True, validators=[Registration.models.validate_akgec_email])),
                ('living_type', models.CharField(choices=[('hosteller', 'Hosteller'), ('day scholar', 'Day Scholar')], max_length=20)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('email_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
