# Generated by Django 5.2 on 2025-04-12 07:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_registration_order_id_registration_payment_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='full_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Full name must contain only letters and spaces.', regex='^[A-Za-z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='registration',
            name='student_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Student number must be numeric.', regex='^\\d+$')]),
        ),
    ]
