# Generated by Django 5.2 on 2025-04-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0003_alter_registration_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
    ]
